springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

app:
  admin:
    username: ${APP_ADMIN_USERNAME}
    password: ${APP_ADMIN_PASSWORD}
    nickname: ${APP_ADMIN_NICKNAME:系统管理员}
  jwt:
    secret: ${APP_JWT_SECRET}
